name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compilepawn:
    runs-on: ubuntu-latest
    container: sacnr/pawncc
    steps:
      - uses: actions/checkout@v1
      - run: /pawnc/bin/pawncc main
        name: Test
      - name: Upload amx
        uses: actions/upload-artifact@v2
        with: 
          name: main.amx
          path: /samp/main.amx
